version: '4'
services:
  mongodb:
    image: mongo:7.0.5
    container_name: shopDEV
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    environment:
#      - MONGO_INITDB_ROOT_USERNAME=admin
#      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=shopDEV

#PERSISTENT VOLUMES
volumes:
  mongodb:
    driver: local

