@url_dev=http://localhost:3001/v1/api/
### get products
GET {{url_dev}}/product/published/all
Content-Type: application/json
x-api-key: 49305ed91328f36506a9444a61972687c1fbf1b458fab9f966a8f26fda38dd40a3d8daa0b0f3a8c1023fa47eed3ab8cc8a950f1b630b3ff26706e940a4f47c59
x-client-id: 6713ae3dee14293712897be3
authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzEzYWUzZGVlMTQyOTM3MTI4OTdiZTMiLCJlbWFpbCI6InNob3B0aXBqczlAZ21haWwuY29tIiwiaWF0IjoxNzMzMjMxNzU0LCJleHAiOjE3MzM0MDQ1NTR9.XTeH4mfnntCu1iuXsNnsfsudLzYZC1nN7YZkG4PZEG0
x-rtoken-id: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzEzYWUzZGVlMTQyOTM3MTI4OTdiZTMiLCJlbWFpbCI6InNob3B0aXBqczlAZ21haWwuY29tIiwiaWF0IjoxNzMzMjMxNzU0LCJleHAiOjE3MzM4MzY1NTR9.JXjJAJ8H_NwCgVM26qEwO4BRNuHAM_czoJ01v-0s3Qs